### PR TITLE
fix one time fees services issues

### PR DESCRIPTION
**Pull request by ying-pbrc**
1. one time fees services missing from the sub service request dialog in portal.
2. make sure one time fees services are not displayed twice on review page.

### CODE REVIEW

**Comment by amcates** [comment]
The team is internally reviewing this and will provide feedback.

**Comment by jleonardw9** [comment]
Thanks for pointing out this bug. I had to make a modification in the _otf_calender.html.haml file to account for the duplicates on the review page, but good catch in the portal view. I'm going to delete this pull request and then give you credit in the one I'm going to submit.

**Comment by ying-pbrc** [comment]
No problem. Thanks.

**Comment by amcates** [comment]
Fixed in https://github.com/sparc-request/sparc-request/pull/25

**Pull request closed without merging**
