### PR TITLE
fix otf service report - missing program services

### PR DESCRIPTION
**Pull request by ying-pbrc**
missing program level services if Core is not being used
d

### CODE REVIEW

**Comment by amcates** [comment]
2 issues with this request.

1. Wouldn't core.blank? or core.empty? be a better option than core == ""
2. The loop at the bottom will duplicate data.  You need to loop over programs with no core and programs with cores separately.

**Comment by ying-pbrc** [comment]
Agree. Thanks! I will take care of it.

**Comment by ying-pbrc** [comment]
Thanks for your feedback. I’ve changed core == “” to core.blank? as suggested.

 

After examining the bottom outer loop 

            provider.programs.each do |program|

and testing with various scenarios, I don’t think there is a possibility of getting a duplicate since the two inner loops:  

  program.sub_service_requests.each do |ssr|

    build_one_time_fee_report(csv, ssr, provider, program, "")

 end

and  

  program.cores.each do |core|

    core.sub_service_requests.each do |ssr|

      build_one_time_fee_report(csv, ssr, provider, program, core)

    end 

 end

are mutually exclusive.  

            

However, I came across another issue when the split/notify is checked at the program level for a provider and each program has its own cores: Although there was no major data error in the report, the Core column are all blank. In my test case, the organization_id of the program/cores subservice requests (ssr) are all set to the program instead of their corresponding core. In order to fix this issue, I probably need to modify the build_one_time_fee_report method. Do you have any suggestions? I can make changes to our SPARC instance and delete this pull request if you prefer. 

 

Thanks,

Ying

**Comment by amcates** [comment]
Sorry, I misread the pull request.  I thought the second loop was inside the first.  It should work as you mentioned.

I will have the team re-exam the pull request and accept it.

Thanks!  


We will also look in to what you mentioned about the split/notify issue.

**Comment by ying-pbrc** [comment]
Thanks.

**Pull request merged**
