### PR TITLE
Fix missing inactive services

### PR DESCRIPTION
**Pull request by ying-pbrc**
while it should only shows available services, all services of an existing SSR should be displayed on Step 2.

https://www.pivotaltracker.com/n/projects/1918597/stories/166545762

### CODE REVIEW

**Comment by kayla-glick** [comment]
@ying-pbrc 

This change is going to cause some conflicts on the Bootstrap 4 branch. Would you be able to merge these changes into that branch and make sure that it still works? Thanks

**Comment by ying-pbrc** [comment]
@kayla-glick, will do.

**Comment by ying-pbrc** [comment]
Kayla,
There are some conflicts when I tried to merge these changes into bootstrap-4. I am going to close this PR and add a blocker to the story for now.  I will revisit this when your bootstrap-4 work is complete, perhaps the fix will no longer be needed.

**Comment by ying-pbrc** [comment]
Revisit the issue when bootstrap-4 change is complete

**Comment by ying-pbrc** [comment]
@kayla-glick 
I got the following error when i run bootstrap-4 branch on my machine. Any insight that you can provide will be greatly appreciated. What did I miss
?
ActionView::Template::Error (Error: File to import not found or unreadable: bootstrap/scss/bootstrap.
        on line 26 of app/assets/stylesheets/application.scss
>> @import 'bootstrap/scss/bootstrap';

[bootstrap-error.txt](https://github.com/sparc-request/sparc-request/files/3397945/bootstrap-error.txt)

**Pull request closed without merging**
