### PR TITLE
Service components refactor

### PR DESCRIPTION
**Pull request by jleonardw9**

### CODE REVIEW

**Comment by jug2** [comment]
Thank you.

Can you reference what PT story this pull request is for?
-Lane

**Comment by jug2** [comment]
Hey,

Can you tell me what PT story this is in reference to?
https://github.com/sparc-request/sparc-request/pull/96

**Comment by jleonardw9** [comment]
Yeah, this is for the sparc side of Charlie's components refactor.

**Comment by jug2** [comment]
Awesome! Thanks. Have you done a deploy yet today?

Thanks again,
Lane

**Pull request merged**
