### PR TITLE
extra '' causing error on calendar consolidated request tab

### PR DESCRIPTION
**Pull request by ying-pbrc**
sr error consolidated request tab

### CODE REVIEW

**Comment by jleonardw9** [comment]
Looks good, thanks.

**Comment by jayhardee9** [comment]
Good catch! Can you also fix line 161 in the same file?

**Comment by ying-pbrc** [comment]
good catch, didn't see that one. its updated now.

**Comment by jayhardee9** [comment]
One more thing! It seems that the changes you made are hiding draft services on the Step 2B calendar. If you only compare the SubServiceRequest status against 'first_draft' only (in the two lines you changed), I believe you can fix your error while preserving existing functionality. Sorry for any confusion!

**Comment by ying-pbrc** [comment]
Actually, i am still running on OS v1.7.5, that was probably why i didn't see the 2nd %w('first_draft' 'draft') on line 161 at the first place. In v1.7.5. I don't think i have the most current version of your master branch. I will close this pull request, and do new pull request then submit my fix.

**Comment by ying-pbrc** [comment]
sorry Jay, 
The branch that i submitted my fix was based off your current master branch - i had too many different versions running on my machine. Since I have no knowledge of  any functionality changes in development, i don't want to make any logic change to OS code. This pull request is only meant to fix bug that caused by the unintended typos.

**Comment by ying-pbrc** [comment]
please review. Thanks

**Comment by jayhardee9** [comment]
I understand that was not your intention! It looks good to me now.

**Comment by jleonardw9** [comment]
Ying, this looks great! Thanks for catching this, we'll get you pulled in as soon as the team goes over pull requests. We've got a few production issues we're trying to settle at the moment, so we're on hold for now.

**Comment by ying-pbrc** [comment]
No problems. Thanks for the update.

**Pull request merged**
