### PR TITLE
Additional detail

### PR DESCRIPTION
**Pull request by robertjamesmiller**

### CODE REVIEW

**Comment by robertjamesmiller** [comment]
@wtholt , @jleonardw9 , and @amcates . I updated our additional_detail branch and its pull request with wth-ml-js-file-reorganization-and-upgrade to revert the previously reverted merge so that this pull request becomes mergeable without conflicts. Please merge additional_detail with wth-ml-js-file-reorganization-and-upgrade at your earliest convenience and let me know if you have any questions or need changes from us.

**Comment by amcates** [comment]
Thanks!  We are in maintenance mode until the new year.  Will look at this
first of the year.

**Comment by wtholt** [comment]
@robertjamesmiller Could you please re-submit this pull request to 'wth-upgrade-jquery'. I got a little over my head and ambitious with this branch trying to update the deprecated syntax. On the new branch, I'm using the jQuery migrate plugin which adds back the functionality lost with the upgrade. Once you re-submit the PR, I can merge ASAP. Sorry for the trouble.

**Comment by robertjamesmiller** [comment]
@wtholt will do. The "jQuery migrate plugin" sounds like a great idea, sorry we didn't know about that.

**Pull request closed without merging**
