### PR TITLE
Wth sparc request proper reconfig part two

### PR DESCRIPTION
**Pull request by wtholt**

### CODE REVIEW

**Comment by robertjamesmiller** [comment]
@wtholt can you please add the CSS classes of "btn btn-primary" back to the buttons because those are the Bootstrap classes we use, see:
screen shot 2015-12-10 at 3 58 50 pm

Or, if you have time, can upload a screenshot of what the new buttons will look like?

thanks!

**Comment by amcates** [comment]
Agreed, we are in the process of upgrading so I would add them back to the new buttons

**Comment by wtholt** [comment]
@robertjamesmiller Just added the classes back. I think we can remove 'if @sub_service_request.nil?' from link_to tags, because both of the links are wrapped in that if statement.

**Comment by wtholt** [comment]
screen shot 2015-12-11 at 9 31 02 am

My attempt at making the buttons 'pretty', per request by our project manager.

**Comment by robertjamesmiller** [comment]
@wtholt your buttons look great! for consistency and to give us the option to use either style, please do add the CSS classes "btn btn-primary". thanks!

**Comment by wtholt** [comment]
@amcates How is editing a study or project going to be handled now? @kyle-glick wrote a whole spec file for editing a study or project, this PR causes that file to fail. Reference: spec/features/protocols/projects/identity_edits_project_spec.rb

**Comment by wtholt** [comment]
ready to merge

**Pull request merged**
