### PR TITLE
Non-clinical services for cost analysis report

### PR DESCRIPTION
**Pull request by chrisortman**
https://www.pivotaltracker.com/story/show/171649105

### CODE REVIEW

**Comment by Stuart-Johnson** [comment]
@chrisortman Is this supposed to be put into the already released version (v3.6.x)? I notice it's aimed at master. If this is something for the upcoming release, I can change it to point to v3.7.0.

**Comment by chrisortman** [comment]
Good catch, sorry about that. Should have been against 3.7

**Comment by Stuart-Johnson** [comment]
@chrisortman No problem. You might want to pull the latest v3.7.0 and merge that into this branch, and re-push. I think your spec failures are random ones that have been fixed in v3.7.0, and that will fix those, and re-trigger travis (I can't do it since the branch is in your fork/repo.

**Comment by kayla-glick** [comment]
@Stuart-Johnson It looks like this one just needs to be updated from v3.7.0

**Comment by Stuart-Johnson** [comment]
@chrisortman Hey, there's some funky git history going on because of the original base, etc. I've made a new branch from yours, and am pushing that up in another PR, so it can start fresh, and closing this one, just FYI. New PR is: https://github.com/sparc-request/sparc-request/pull/2333

**Pull request closed without merging**
