### PR TITLE
SRY - Updating Epic question and notes

### PR DESCRIPTION
**Pull request by royyesud**
Story: https://www.pivotaltracker.com/story/show/182736600

### CODE REVIEW

**Review by jleonardw9 — COMMENTED** [review]
@royyesud I've looked at this and reran the specs, and it looks like you have an actual failure in `spec/features/dashboard/protocol/new/user_selects_publish_in_epic_spec.rb` on line 55. Also in sparc proper `/spec/features/proper/protocol/protocols/user_selects_publish_in_epic_spec.rb` line 63. You might have to reconfigure the way that the questions are built in the fixtures to reflect your changes. I think it's `build_study_type_questions`.

**Comment by royyesud** [comment]
@jleonardw9 I have fixed both the specs and committed my changes

**Review by jleonardw9 — APPROVED** [review]
Looks great, @royyesud !

**Comment by jleonardw9** [comment]
@amcates I don't know what you want to do about this one, but the one remaining failing feature test is not related to @royyesud's changes. It's a surveyor test and it passes locally on my machine.

**Pull request merged**
