### PR TITLE
Musc i18n mailer

### PR DESCRIPTION
**Pull request by loganfreeman**
In order to make the test more robust, I changed the rspec to use i18n.

### CODE REVIEW

**Comment by loganfreeman** [comment]
updated the pull request to deal with unit_factor

```
unit_factor || 0
```

will result in 0 if unit_factor is 0, then resulting in division by zero exception

**Comment by loganfreeman** [comment]
```ruby
oe.service_providers.map(&:identity_id)
```


should use `&:identity_id` instead of `&:id`

**Comment by kyle-glick** [comment]
@loganfreeman 
Can you merge master into this branch and push it back up? It should fix the spec timeout.

**Comment by loganfreeman** [comment]
@kyle-glick 
I merged sparc-request/master into musc-i18n-mailer and pushed it back.

**Pull request closed without merging**
